### ISSUE TITLE
Slowing Effect

### ISSUE THREAD

**Issue by JamsRepos** [Ilusion9/sm-csgo-molotov-damage#1]
How do you propose to solve the issue where if a team mate knives/shoots you, your movement speed is lowered? This could still be a huge issue.

**Comment by Ilusion9** [comment]
That can be done with SDK Trace function. I will look into it and will come back with an update.

**Comment by JamsRepos** [comment]
Sweet, cheers.

**Comment by Ilusion9** [comment]
I've updated the plugin. Can you try it?
