### ISSUE TITLE
Inspirations from other plugins

### ISSUE THREAD

**Issue by borzaka** [Ilusion9/sm-csgo-molotov-damage#2]
Thank you for your work. I try to give you my experience with some other plugins like yours. And maybe you can combine the best practice.

First, I have used [foreach's](https://forums.alliedmods.net/showthread.php?t=301081) plugin.
Problems I had with it:
- No bomb explode damage
- No fall damage (I opened a[ pull request](https://github.com/lucasgolino/comp_noff/pull/3) to fix this, but it's not accepted yet, but it was worked for me - I saw the solution at the forum thread)

After that I used [Ilusion9's](https://forums.alliedmods.net/showpost.php?p=2639336&postcount=2) version. I believe it's yours early version.
And I'am still using it, and it's working fine.

So, this repo is a complete rewrite? Better in every way than others?
Thanks for the cvars for setting the `ff_damage_reduction_`*, that's a great idea!

**Comment by Ilusion9** [comment]
Yes, it's a complete rewrite. C4 does damage as normal, and fall damage works normal.

**Comment by Khayenoh** [comment]
could you add the damage with the other grenades? and when they hit you with a decoil for example
