### ISSUE TITLE
Not working after last update

### ISSUE THREAD

**Issue by 39ma** [Ilusion9/sm-csgo-molotov-damage#4]
Not working after last update

**Comment by borzaka** [comment]
I can confirm, that after this update, the plugin is not blocking friendly fire anymore:
https://blog.counter-strike.net/index.php/2020/07/30991/

**Update:**
Probably a SourceMod update will fix the issue:
https://www.sourcemod.net/downloads.php?branch=stable

**Comment by crashzk** [comment]
As far as I could see SourceMod version 1.10 doesn't work, only with the SourceMod 1.11 dev version that works again.

**Comment by borzaka** [comment]
For me it's working fine. Maybe this commit broke it? 86fb8460b7a3684172bfe1915f80366a09aafdc9

**Comment by Ilusion9** [comment]
> 
> 
> For me it's working fine. Maybe this commit broke it? [86fb846](https://github.com/Ilusion9/molotov-friendlyfire-sm/commit/86fb8460b7a3684172bfe1915f80366a09aafdc9)

No, that could never break the plugin.
Just update the sm and metamod to the latest stable versions (there was a problem with SDK_OnTakeDamage on one of the latest csgo updates).
