### ISSUE TITLE
Errors SM 1.10 - build 6492

### ISSUE THREAD

**Issue by igorik** [Ilusion9/sm-csgo-molotov-damage#5]
L 07/28/2020 - 17:53:36: [SM] Exception reported: Client 7 is not in game
L 07/28/2020 - 17:53:36: [SM] Blaming: molotov_friendlyfire.smx
L 07/28/2020 - 17:53:36: [SM] Call stack trace:
L 07/28/2020 - 17:53:36: [SM]   [0] GetClientTeam
L 07/28/2020 - 17:53:36: [SM]   [1] Line 46, C:\Users\Igorik\Desktop\compil6492\addons\sourcemod\scripting\molotov_friendlyfire.sp::SDK_OnTakeDamage
L 07/28/2020 - 17:53:36: [SM] Exception reported: Client 7 is not in game
L 07/28/2020 - 17:53:36: [SM] Blaming: molotov_friendlyfire.smx
L 07/28/2020 - 17:53:36: [SM] Call stack trace:
L 07/28/2020 - 17:53:36: [SM]   [0] GetClientTeam
L 07/28/2020 - 17:53:36: [SM]   [1] Line 46, C:\Users\Igorik\Desktop\compil6492\addons\sourcemod\scripting\molotov_friendlyfire.sp::SDK_OnTakeDamage
L 07/28/2020 - 17:53:36: [SM] Exception reported: Client 7 is not in game
L 07/28/2020 - 17:53:36: [SM] Blaming: molotov_friendlyfire.smx
L 07/28/2020 - 17:53:36: [SM] Call stack trace:
L 07/28/2020 - 17:53:36: [SM]   [0] GetClientTeam
L 07/28/2020 - 17:53:36: [SM]   [1] Line 46, C:\Users\Igorik\Desktop\compil6492\addons\sourcemod\scripting\molotov_friendlyfire.sp::SDK_OnTakeDamage
L 07/28/2020 - 17:53:36: [SM] Exception reported: Client 7 is not in game
L 07/28/2020 - 17:53:36: [SM] Blaming: molotov_friendlyfire.smx
L 07/28/2020 - 17:53:36: [SM] Call stack trace:
L 07/28/2020 - 17:53:36: [SM]   [0] GetClientTeam
L 07/28/2020 - 17:53:36: [SM]   [1] Line 46, C:\Users\Igorik\Desktop\compil6492\addons\sourcemod\scripting\molotov_friendlyfire.sp::SDK_OnTakeDamage
L 07/28/2020 - 17:53:36: [SM] Exception reported: Client 7 is not in game
L 07/28/2020 - 17:53:36: [SM] Blaming: molotov_friendlyfire.smx
L 07/28/2020 - 17:53:36: [SM] Call stack trace:
L 07/28/2020 - 17:53:36: [SM]   [0] GetClientTeam
L 07/28/2020 - 17:53:36: [SM]   [1] Line 46, C:\Users\Igorik\Desktop\compil6492\addons\sourcemod\scripting\molotov_friendlyfire.sp::SDK_OnTakeDamage
L 07/28/2020 - 17:53:37: [SM] Exception reported: Client 7 is not in game
L 07/28/2020 - 17:53:37: [SM] Blaming: molotov_friendlyfire.smx
L 07/28/2020 - 17:53:37: [SM] Call stack trace:
L 07/28/2020 - 17:53:37: [SM]   [0] GetClientTeam
L 07/28/2020 - 17:53:37: [SM]   [1] Line 46, C:\Users\Igorik\Desktop\compil6492\addons\sourcemod\scripting\molotov_friendlyfire.sp::SDK_OnTakeDamage
L 07/28/2020 - 17:53:37: [SM] Exception reported: Client 7 is not in game
L 07/28/2020 - 17:53:37: [SM] Blaming: molotov_friendlyfire.smx
L 07/28/2020 - 17:53:37: [SM] Call stack trace:
L 07/28/2020 - 17:53:37: [SM]   [0] GetClientTeam
L 07/28/2020 - 17:53:37: [SM]   [1] Line 46, C:\Users\Igorik\Desktop\compil6492\addons\sourcemod\scripting\molotov_friendlyfire.sp::SDK_OnTakeDamage
L 07/28/2020 - 17:53:37: [SM] Exception reported: Client 7 is not in game
L 07/28/2020 - 17:53:37: [SM] Blaming: molotov_friendlyfire.smx
L 07/28/2020 - 17:53:37: [SM] Call stack trace:
L 07/28/2020 - 17:53:37: [SM]   [0] GetClientTeam
L 07/28/2020 - 17:53:37: [SM]   [1] Line 46, C:\Users\Igorik\Desktop\compil6492\addons\sourcemod\scripting\molotov_friendlyfire.sp::SDK_OnTakeDamage
L 07/28/2020 - 17:53:37: [SM] Exception reported: Client 7 is not in game
L 07/28/2020 - 17:53:37: [SM] Blaming: molotov_friendlyfire.smx
L 07/28/2020 - 17:53:37: [SM] Call stack trace:
L 07/28/2020 - 17:53:37: [SM]   [0] GetClientTeam
L 07/28/2020 - 17:53:37: [SM]   [1] Line 46, C:\Users\Igorik\Desktop\compil6492\addons\sourcemod\scripting\molotov_friendlyfire.sp::SDK_OnTakeDamage
L 07/28/2020 - 19:26:39: Error log file session closed.

**Comment by raufGarayev** [comment]
+1
