### ISSUE TITLE
Implement Level Punishment System

### ISSUE THREAD

**Issue by crashzk** [Ilusion9/sm-csgo-molotov-damage#6]
Implement a punishment system for players who kill their friends by friendly fire, for example:

- Player does 170 friendly fire damage and gets kicked;
- Player returns and does 170 friendly fire damage and is temporarily banished;
- Player returns and does 170 friendly fire damage takes permanent banishment;

Before reaching 170 damage with friendly fire the player is notified, if continuing with friendly fire will be punished.

**_Note: If compatible with SourceBans++._**

### HOW WOULD IT WORK

Create a cvar to control the amount of friendly fire a player can give before taking a penalty.

**- `ff_damage_limit "X"`** - X would be the limit of damage the player can do before being punished;

This limit will only reset if the player gets a kick from the plugin or if the map is changed, otherwise it saves the information/amount of damage he did to his friends. This prevents players from giving retry/reconnect to not take punishments.

Punishments would be per level, after making the friendly fire limit he is kicked first, if he returns and continues with friendly fire, when he hits the friendly fire limit again he is punished with the second level, temporary ban in the case and so on against.

It would be interesting if in each punishment level you could configure the reason for kicks/bans and the time for each ban.

**Comment by Ilusion9** [comment]
That should be implemented in another plugin, a new one.
