### ISSUE TITLE
Isn't working

### ISSUE THREAD

**Issue by NaathySz** [Ilusion9/sm-csgo-molotov-damage#8]
Hi! i use this plugin an time ago with splewis pugsetup. It workd for some time, but for some reason (idk) plugin just stop to work.
i have mp_friendlyfire 1
cfg not create too since i installed, so i put cvars in live.cfg (and work in a short time)
this is cvars i config:

sm_cvar sm_ff_damage_reduction_hegrenade 0
sm_cvar sm_ff_damage_reduction_hegrenade_self 1.0
sm_cvar sm_ff_damage_reduction_molotov 1.0
sm_cvar sm_ff_damage_reduction_molotov_self 1.0
sm_cvar sm_ff_damage_reduction_knife 0.0
sm_cvar sm_ff_damage_reduction_taser 0.0
sm_cvar sm_ff_damage_reduction_other 0.0

not errors too. Plugins is loaded without errors, cvars are setted without errors, but the molotov damage isnt working

**Comment by Ilusion9** [comment]
Test the plugin without splewis pugsetup

**Comment by NaathySz** [comment]
Plugin unload every match. I fixed putting `sm_rcon sm plugins load nameofplugin` in live.cfg
Thank you and sorry for long time.
