### ISSUE TITLE
Slowing effect (again?)

### ISSUE THREAD

**Issue by NaathySz** [Ilusion9/sm-csgo-molotov-damage#9]
Hi. As the first issue of this page, im got the same issue. When you knife or shoot some teammate, their move speed slow soo much.
There's some fix for it? i downloaded latest version.

Sorry my broken english, hope you can understand what im getting.

**Comment by Khayenoh** [comment]
You fix this?

**Comment by NaathySz** [comment]
> You fix this?

nope

**Comment by Ilusion9** [comment]
check friendly_fire_v2.sp

**Comment by NaathySz** [comment]
> check friendly_fire_v2.sp

Slow effect stopped, but now the friendly fire not work xd

**Comment by NaathySz** [comment]
Well, i've solved this

**Comment by KevinllBin** [comment]
> Well, i've solved this

how did you solve it ,  can u share it with me

**Comment by NaathySz** [comment]
> > Well, i've solved this
> 
> how did you solve it , can u share it with me

Yeah, of course, but was not with Ilusion plugin. I was wanting enable FriendlyFire only in molotov and disable in all others, so its better do a plugin that doesnt have other functions

Anyway, if you still want it, here is 
[MolotovFF.zip](https://github.com/Ilusion9/csgo-ff-damage-sm/files/9480141/MolotovFF.zip)


And please, note that it will only work with these cvars:

```
ff_damage_bullet_penetration 0
ff_damage_decoy_explosion 0
ff_damage_grenade_hit 0
ff_damage_reduction_bullets 0
ff_damage_reduction_grenade 0
ff_damage_reduction_grenade_self 1
ff_damage_reduction_other 1
```

**Comment by KevinllBin** [comment]
> 



> > > Well, i've solved this
> > 
> > 
> > how did you solve it , can u share it with me
> 
> Yeah, of course, but was not with Ilusion plugin. I was wanting enable FriendlyFire only in molotov and disable in all others, so its better do a plugin that doesnt have other functions
> 
> Anyway, if you still want it, here is [MolotovFF.zip](https://github.com/Ilusion9/csgo-ff-damage-sm/files/9480141/MolotovFF.zip)
> 
> And please, note that it will only work with these cvars:
> 
> ```
> ff_damage_bullet_penetration 0
> ff_damage_decoy_explosion 0
> ff_damage_grenade_hit 0
> ff_damage_reduction_bullets 0
> ff_damage_reduction_grenade 0
> ff_damage_reduction_grenade_self 1
> ff_damage_reduction_other 1
> ```

thx
